version: '3'

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile.dev
        volumes:
            - ./frontend:/usr/share/nginx/html
            - ./frontend/conf:/etc/nginx/conf.d
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend:/app
